import { buildCompanyFeatures } from '@/entities/loan-company/lib/buildCompanyFeatures';
import { buildCompanyProductDetail } from '@/entities/loan-company/lib/buildCompanyProductDetail';
import { buildCompanyRegistration } from '@/entities/loan-company/lib/buildCompanyRegistration';
import {
  BITNA_SUPPLEMENTARY_DESCRIPTION,
  buildSupplementaryDescription,
} from '@/entities/loan-company/lib/buildSupplementaryDescription';
import { generateExtraMockCompanies } from '@/entities/loan-company/model/generateExtraMockCompanies';

import type { Company } from './types';

const mockCompanySource: Company[] = [
  {
    id: 'company-1',
    name: '든든금융대부',
    tagline: '강남·서초 직장인 맞춤 소액대출',
    summary: '비대면 서류 접수 가능, 당일 한도 조회 상담.',
    regionLabel: '서울',
    regionLabels: ['서울', '경기','대구','인천','부산'],
    region: '서울 강남구',
    products: ['소액대출', '직장인대출', '무방문대출', '비대면대출'],
    loanLimit: '최대 3,000만원',
    interestRate: '연 12% ~ 20%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '02-1234-5678',
    isVerifiedAvailable: true,
    isRecommended: true,
    isAd: false,
    features: ['24시간 상담', '당일승인', '무방문'],
    consultationType: 'both',
    consultationTime: '09:00 ~ 22:00',
    description:
      '서울 강남·서초 지역 직장인·사업자 대상 소액·비상금 대출 상담을 제공합니다.',
    additionalCost: '중도상환수수료 없음 (조건별 상이)',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-2',
    name: '서울희망금융',
    tagline: '마포·은평 당일 한도 조회',
    summary: '비상금·신용대출, 직장인·프리랜서 대상.',
    regionLabel: '서울',
    region: '서울 마포구',
    products: ['비상금대출', '신용대출', '당일대출', '여성대출'],
    loanLimit: '최대 5,000만원',
    interestRate: '연 14% ~ 24%',
    repaymentMethod: '원리금균등',
    contactNumber: '02-2345-6789',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: true,
    features: ['당일승인', '직장인', '비상금'],
    consultationType: 'phone',
    consultationTime: '10:00 ~ 20:00',
    description: '마포·은평 지역 맞춤 대출 상담. 당일 한도 조회 가능.',
    situations: ['직장인', '프리랜서', '여성'],
  },
  {
    id: 'company-3',
    name: '부산안심대부',
    tagline: '부산·울산 소액대출 전문',
    summary: '무직자·주부도 상담 가능, 문자 상담 운영.',
    regionLabel: '부산',
    region: '부산 해운대구',
    products: ['소액대출', '무직자대출', '주부대출'],
    loanLimit: '최대 1,000만원',
    interestRate: '연 15% ~ 22%',
    repaymentMethod: '만기일시',
    contactNumber: '051-345-6789',
    isVerifiedAvailable: false,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 18:00',
    description: '부산·울산 지역 소액대출 전문.',
    situations: ['무직자', '주부'],
  },
  {
    id: 'company-4',
    name: '경기믿음금융',
    tagline: '수원·용인·화성 직장인·사업자',
    summary: '소액·당일대출 상담, 평일·주말 연장 운영.',
    regionLabel: '경기',
    region: '경기 수원시',
    products: ['소액대출', '당일대출', '사업자대출', '자영업자대출'],
    loanLimit: '최대 2,000만원',
    interestRate: '연 13% ~ 19%',
    repaymentMethod: '원리금균등',
    contactNumber: '031-456-7890',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 21:00',
    description: '수원·용인·화성 지역 직장인·사업자 대출 상담.',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-5',
    name: '인천스마트대부',
    tagline: '인천 전역 무방문·비대면',
    summary: '비상금·무방문 대출, 주부·여성 맞춤 상담.',
    regionLabel: '인천',
    region: '인천 남동구',
    products: ['무방문대출', '비상금대출', '비대면대출', '모바일대출'],
    loanLimit: '최대 2,500만원',
    interestRate: '연 11% ~ 18%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '032-567-8901',
    isVerifiedAvailable: true,
    isRecommended: true,
    isAd: true,
    features: ['무방문', '24시간 상담', '비상금'],
    consultationType: 'phone',
    consultationTime: '08:30 ~ 22:30',
    description: '인천 전역 비대면·무방문 대출 상담.',
    situations: ['직장인', '주부', '여성'],
  },
  {
    id: 'company-6',
    name: '대구한결금융',
    tagline: '대구·경북 맞춤 대출 상담',
    summary: '신용·소액대출, 직장인·프리랜서 대상.',
    regionLabel: '대구',
    region: '대구 수성구',
    products: ['신용대출', '소액대출', '프리랜서대출'],
    loanLimit: '최대 4,000만원',
    interestRate: '연 16% ~ 25%',
    repaymentMethod: '원리금균등',
    contactNumber: '053-678-9012',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 19:00',
    description: '대구·경북 지역 맞춤 대출.',
    situations: ['직장인', '프리랜서'],
  },
  {
    id: 'company-7',
    name: '광주희망대부',
    tagline: '광주·전남 소액·비상금',
    summary: '무직자·주부 상담 가능, 문자 접수 운영.',
    regionLabel: '광주',
    region: '광주 서구',
    products: ['소액대출', '비상금대출', '생활비대출'],
    loanLimit: '최대 1,500만원',
    interestRate: '연 14% ~ 21%',
    repaymentMethod: '만기일시',
    contactNumber: '062-789-0123',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 18:00',
    description: '광주·전남 지역 소액·비상금 대출 상담.',
    situations: ['무직자', '주부', '여성'],
  },
  {
    id: 'company-8',
    name: '제주안심금융',
    tagline: '제주 거주자 비대면 상담',
    summary: '소액·무방문 대출, 사업자·프리랜서 가능.',
    regionLabel: '제주',
    region: '제주 제주시',
    products: ['소액대출', '무방문대출', '온라인대출'],
    loanLimit: '최대 2,000만원',
    interestRate: '연 13% ~ 20%',
    repaymentMethod: '원리금균등',
    contactNumber: '064-890-1234',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 17:30',
    description: '제주 지역 거주자 대상 비대면 상담.',
    situations: ['직장인', '사업자', '프리랜서'],
  },
  {
    id: 'company-9',
    name: '전국희망금융',
    tagline: '전국 비대면 소액대출',
    summary: '지역 제한 없이 전화·문자 상담 가능.',
    regionLabel: '전국',
    region: '전국',
    products: ['소액대출', '비상금대출', '무방문대출', '온라인대출'],
    loanLimit: '최대 3,500만원',
    interestRate: '연 12% ~ 22%',
    repaymentMethod: '원리금균등',
    contactNumber: '1588-0000',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '08:00 ~ 23:00',
    description: '전국 어디서나 비대면 소액·비상금 대출 상담.',
    situations: ['직장인', '무직자', '주부'],
  },
  {
    id: 'company-10',
    name: '빛나대부중개',
    tagline: '24시 비대면 월변대출 최대한도 승인율UP',
    summary: '전국 비대면 당일 승인·입금, 소득 있으면 직군 무관 상담.',
    regionLabel: '대전',
    region: '대전광역시 서구 월평북로 85, 355호 (월평동)',
    products: ['월변대출', '비대면대출', '당일대출', '소액대출'],
    loanLimit: '상담',
    interestRate: '연 10% ~ 18%',
    repaymentMethod: '상담 후 결정',
    contactNumber: '010-8104-7147',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    features: ['24시간 상담', '당일승인', '무방문'],
    consultationType: 'both',
    consultationTime: '365일 24시간',
    description:
      '고객님과의 신뢰를 가장 중요하게 생각하는 정식 등록 대부중개 업체입니다. 당일 승인·입금 중심으로 빠르게 상담해 드립니다.',
    supplementaryDescription: BITNA_SUPPLEMENTARY_DESCRIPTION,
    additionalCost: '무',
    situations: ['직장인', '사업자', '무직자', '저신용자'],
    registration: {
      registrationNumber: '대전-4231',
      representativeName: '강동균',
      registrationAuthority: '대전 대전광역시 경제정책과',
      registrationAuthorityPhone: '042-270-3516',
      officeAddress: '대전광역시 서구 월평북로 85, 355호 (월평동)',
    },
    productDetail: {
      monthlyInterestRate: '월 1% ~ 1.6%',
      annualInterestRate: '연 10% ~ 18%',
      loanLimit: '상담',
      overdueInterestRate: '없음',
      additionalCost: '무',
      earlyRepaymentFee: '무',
      repaymentMethod: '상담 후 결정',
      loanPeriod: '상담',
      serviceRegion: '전국',
    },
  },
  {
    id: 'company-11',
    name: '울산바로대부',
    tagline: '울산 당일·비상금',
    summary: '당일대출·비상금, 저신용자 상담 가능.',
    regionLabel: '울산',
    region: '울산 남구',
    products: ['당일대출', '비상금대출', '저신용자대출'],
    loanLimit: '최대 1,800만원',
    interestRate: '연 14% ~ 23%',
    repaymentMethod: '만기일시',
    contactNumber: '052-222-3333',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: true,
    consultationType: 'both',
    consultationTime: '08:00 ~ 21:00',
    situations: ['직장인', '무직자'],
  },
  {
    id: 'company-12',
    name: '세종안심금융',
    tagline: '세종시 맞춤 비대면',
    summary: '공무원·직장인 대상 신용·소액 상담.',
    regionLabel: '세종',
    region: '세종 조치원읍',
    products: ['신용대출', '소액대출', '비대면대출'],
    loanLimit: '최대 2,000만원',
    interestRate: '연 12% ~ 19%',
    repaymentMethod: '원리금균등',
    contactNumber: '044-333-4444',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 18:00',
    situations: ['직장인'],
  },
  {
    id: 'company-13',
    name: '강원희망대부',
    tagline: '강원도 소액·생활비',
    summary: '춘천·원주 지역 생활비·소액 상담.',
    regionLabel: '강원',
    region: '강원 춘천시',
    products: ['소액대출', '생활비대출', '비상금대출'],
    loanLimit: '최대 1,200만원',
    interestRate: '연 15% ~ 22%',
    repaymentMethod: '원리금균등',
    contactNumber: '033-444-5555',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 17:00',
    situations: ['직장인', '주부'],
  },
  {
    id: 'company-14',
    name: '충북믿음금융',
    tagline: '청주·충북 직장인',
    summary: '직장인·사업자 소액·당일 상담.',
    regionLabel: '충북',
    region: '충북 청주시',
    products: ['직장인대출', '소액대출', '당일대출'],
    loanLimit: '최대 2,200만원',
    interestRate: '연 13% ~ 20%',
    repaymentMethod: '원리금균등',
    contactNumber: '043-555-6666',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 19:00',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-15',
    name: '충남스마트대부',
    tagline: '천안·아산 비대면',
    summary: '무방문·온라인 대출, 프리랜서 가능.',
    regionLabel: '충남',
    region: '충남 천안시',
    products: ['무방문대출', '온라인대출', '프리랜서대출'],
    loanLimit: '최대 2,800만원',
    interestRate: '연 12% ~ 21%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '041-666-7777',
    isVerifiedAvailable: true,
    isRecommended: true,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '08:30 ~ 22:00',
    situations: ['직장인', '프리랜서'],
  },
  {
    id: 'company-16',
    name: '전북한결대부',
    tagline: '전주·전북 맞춤',
    summary: '주부·여성·소액 상담 운영.',
    regionLabel: '전북',
    region: '전북 전주시',
    products: ['소액대출', '주부대출', '여성대출'],
    loanLimit: '최대 1,600만원',
    interestRate: '연 14% ~ 22%',
    repaymentMethod: '만기일시',
    contactNumber: '063-777-8888',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 18:00',
    situations: ['주부', '여성', '무직자'],
  },
  {
    id: 'company-17',
    name: '전남희망금융',
    tagline: '목포·여수 생활비',
    summary: '생활비·비상금, 일용직 상담.',
    regionLabel: '전남',
    region: '전남 목포시',
    products: ['생활비대출', '비상금대출', '일용직대출'],
    loanLimit: '최대 1,400만원',
    interestRate: '연 15% ~ 23%',
    repaymentMethod: '원리금균등',
    contactNumber: '061-888-9999',
    isVerifiedAvailable: false,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 17:30',
    situations: ['무직자', '프리랜서'],
  },
  {
    id: 'company-18',
    name: '경북안심대부',
    tagline: '포항·경북 사업자',
    summary: '사업자·자영업자 추가·대환 상담.',
    regionLabel: '경북',
    region: '경북 포항시',
    products: ['사업자대출', '자영업자대출', '추가대출', '대환대출'],
    loanLimit: '최대 5,000만원',
    interestRate: '연 13% ~ 24%',
    repaymentMethod: '원리금균등',
    contactNumber: '054-999-0000',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: true,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 20:00',
    situations: ['사업자'],
  },
  {
    id: 'company-19',
    name: '경남믿음금융',
    tagline: '창원·경남 직장인',
    summary: '직장인·전문직 신용·소액 상담.',
    regionLabel: '경남',
    region: '경남 창원시',
    products: ['직장인대출', '전문직대출', '신용대출'],
    loanLimit: '최대 4,500만원',
    interestRate: '연 12% ~ 22%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '055-000-1111',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 21:00',
    situations: ['직장인'],
  },
  {
    id: 'company-20',
    name: '서울오토파이낸스',
    tagline: '자동차·부동산 담보',
    summary: '자동차·부동산 담보 대출 전문 상담.',
    regionLabel: '서울',
    region: '서울 송파구',
    products: ['자동차대출', '부동산대출', '추가대출'],
    loanLimit: '최대 1억원',
    interestRate: '연 10% ~ 18%',
    repaymentMethod: '원리금균등',
    contactNumber: '02-999-8888',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '10:00 ~ 19:00',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-21',
    name: '회생희망대부',
    tagline: '회생·파산 후 재기',
    summary: '회생파산 이력자 맞춤 소액 상담.',
    regionLabel: '서울',
    region: '서울 영등포구',
    products: ['회생파산대출', '저신용자대출', '소액대출'],
    loanLimit: '최대 800만원',
    interestRate: '연 17% ~ 26%',
    repaymentMethod: '만기일시',
    contactNumber: '02-777-6666',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 18:00',
    situations: ['무직자', '직장인'],
  },
  {
    id: 'company-22',
    name: '전당포안심금융',
    tagline: '전당포·담보 소액',
    summary: '전당포·기타 담보 소액 상담.',
    regionLabel: '인천',
    region: '인천 부평구',
    products: ['전당포대출', '기타대출', '소액대출'],
    loanLimit: '최대 500만원',
    interestRate: '연 18% ~ 28%',
    repaymentMethod: '만기일시',
    contactNumber: '032-111-9999',
    isVerifiedAvailable: false,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 17:00',
    situations: ['무직자'],
  },
  {
    id: 'company-23',
    name: '노원믿음대부',
    tagline: '노원·도봉 직장인 소액',
    summary: '직장인·사업자 당일 한도 조회, 야간 상담 가능.',
    regionLabel: '서울',
    region: '서울 노원구',
    products: ['직장인대출', '소액대출', '당일대출'],
    loanLimit: '최대 2,500만원',
    interestRate: '연 13% ~ 21%',
    repaymentMethod: '원리금균등',
    contactNumber: '02-901-1001',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 21:00',
    description: '노원·도봉·의정부 인접 지역 직장인 대출 상담.',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-24',
    name: '성남희망금융',
    tagline: '분당·판교 IT 직장인',
    summary: '전문직·직장인 신용·비상금 상담.',
    regionLabel: '경기',
    region: '경기 성남시 분당구',
    products: ['직장인대출', '전문직대출', '비상금대출', '신용대출'],
    loanLimit: '최대 6,000만원',
    interestRate: '연 11% ~ 19%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '031-701-2002',
    isVerifiedAvailable: true,
    isRecommended: true,
    isAd: true,
    consultationType: 'phone',
    consultationTime: '08:00 ~ 22:00',
    description: '분당·판교·성남 지역 직장인·전문직 맞춤 상담.',
    situations: ['직장인'],
  },
  {
    id: 'company-25',
    name: '고양스마트대부',
    tagline: '일산·킨텍스 비대면',
    summary: '무방문·모바일 대출, 주부·여성 가능.',
    regionLabel: '경기',
    region: '경기 고양시 일산동구',
    products: ['무방문대출', '모바일대출', '비대면대출', '주부대출'],
    loanLimit: '최대 3,000만원',
    interestRate: '연 12% ~ 20%',
    repaymentMethod: '원리금균등',
    contactNumber: '031-902-3003',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 22:00',
    situations: ['직장인', '주부', '여성'],
  },
  {
    id: 'company-26',
    name: '종로한결금융',
    tagline: '종로·중구 소상공인',
    summary: '자영업자·사업자 소액·추가 상담.',
    regionLabel: '서울',
    region: '서울 종로구',
    products: ['자영업자대출', '사업자대출', '소액대출', '추가대출'],
    loanLimit: '최대 3,500만원',
    interestRate: '연 14% ~ 23%',
    repaymentMethod: '만기일시',
    contactNumber: '02-803-4004',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:30 ~ 19:00',
    situations: ['사업자'],
  },
  {
    id: 'company-27',
    name: '사하안심대부',
    tagline: '사하·하단 무직자 소액',
    summary: '무직자·주부 소액, 문자 상담 운영.',
    regionLabel: '부산',
    region: '부산 사하구',
    products: ['무직자대출', '주부대출', '소액대출'],
    loanLimit: '최대 900만원',
    interestRate: '연 16% ~ 24%',
    repaymentMethod: '만기일시',
    contactNumber: '051-804-5005',
    isVerifiedAvailable: false,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 18:00',
    situations: ['무직자', '주부'],
  },
  {
    id: 'company-28',
    name: '서구믿음금융',
    tagline: '대전 서구 직장인',
    summary: '직장인·프리랜서 신용 상담.',
    regionLabel: '대전',
    region: '대전 서구',
    products: ['직장인대출', '프리랜서대출', '신용대출'],
    loanLimit: '최대 2,800만원',
    interestRate: '연 13% ~ 22%',
    repaymentMethod: '원리금균등',
    contactNumber: '042-905-6006',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 20:00',
    situations: ['직장인', '프리랜서'],
  },
  {
    id: 'company-29',
    name: '연수바로대부',
    tagline: '송도·연수 당일',
    summary: '당일대출·비상금, 직장인 대상.',
    regionLabel: '인천',
    region: '인천 연수구',
    products: ['당일대출', '비상금대출', '직장인대출'],
    loanLimit: '최대 2,200만원',
    interestRate: '연 12% ~ 21%',
    repaymentMethod: '원리금균등',
    contactNumber: '032-906-7007',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: true,
    consultationType: 'phone',
    consultationTime: '08:30 ~ 21:30',
    situations: ['직장인'],
  },
  {
    id: 'company-30',
    name: '모바일희망금융',
    tagline: '전국 모바일·온라인',
    summary: '앱·온라인 접수, 전국 비대면 상담.',
    regionLabel: '전국',
    region: '전국',
    products: ['모바일대출', '온라인대출', '비대면대출', '소액대출'],
    loanLimit: '최대 4,000만원',
    interestRate: '연 11% ~ 20%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '1588-3030',
    isVerifiedAvailable: true,
    isRecommended: true,
    isAd: true,
    features: ['24시간 상담', '모바일', '비대면'],
    consultationType: 'both',
    consultationTime: '00:00 ~ 24:00',
    description: '전국 어디서나 모바일·온라인으로 접수 가능한 비대면 대출 상담.',
    situations: ['직장인', '프리랜서', '주부'],
  },
  {
    id: 'company-31',
    name: '우먼케어대부',
    tagline: '여성·주부 전문',
    summary: '여성·주부 맞춤 소액·생활비 상담.',
    regionLabel: '서울',
    region: '서울 서초구',
    products: ['여성대출', '주부대출', '생활비대출', '소액대출'],
    loanLimit: '최대 1,500만원',
    interestRate: '연 14% ~ 22%',
    repaymentMethod: '원리금균등',
    contactNumber: '02-907-8008',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 20:00',
    situations: ['여성', '주부'],
  },
  {
    id: 'company-32',
    name: '부천믿음금융',
    tagline: '부천·김포 직장인',
    summary: '직장인 소액·신용, 평일 야간 상담.',
    regionLabel: '경기',
    region: '경기 부천시',
    products: ['직장인대출', '소액대출', '신용대출'],
    loanLimit: '최대 2,400만원',
    interestRate: '연 13% ~ 20%',
    repaymentMethod: '원리금균등',
    contactNumber: '032-908-9009',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 21:00',
    situations: ['직장인'],
  },
  {
    id: 'company-33',
    name: '아산스마트대부',
    tagline: '아산·천안 동부',
    summary: '무방문·당일, 직장인·사업자.',
    regionLabel: '충남',
    region: '충남 아산시',
    products: ['무방문대출', '당일대출', '사업자대출'],
    loanLimit: '최대 2,600만원',
    interestRate: '연 12% ~ 20%',
    repaymentMethod: '원리금균등',
    contactNumber: '041-909-1010',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '08:00 ~ 20:00',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-34',
    name: '원주희망대부',
    tagline: '원주·횡성 생활비',
    summary: '생활비·비상금, 지역 거주자 대상.',
    regionLabel: '강원',
    region: '강원 원주시',
    products: ['생활비대출', '비상금대출', '소액대출'],
    loanLimit: '최대 1,300만원',
    interestRate: '연 15% ~ 23%',
    repaymentMethod: '만기일시',
    contactNumber: '033-910-1111',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 17:30',
    situations: ['직장인', '주부'],
  },
  {
    id: 'company-35',
    name: '익산한결금융',
    tagline: '익산·전주 인접',
    summary: '소액·신용, 무직자·주부 상담.',
    regionLabel: '전북',
    region: '전북 익산시',
    products: ['소액대출', '신용대출', '무직자대출'],
    loanLimit: '최대 1,400만원',
    interestRate: '연 15% ~ 23%',
    repaymentMethod: '원리금균등',
    contactNumber: '063-911-1212',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 18:00',
    situations: ['무직자', '주부', '직장인'],
  },
  {
    id: 'company-36',
    name: '김해바로대부',
    tagline: '김해·부산 서부',
    summary: '직장인·사업자 당일·추가 상담.',
    regionLabel: '경남',
    region: '경남 김해시',
    products: ['당일대출', '사업자대출', '추가대출', '직장인대출'],
    loanLimit: '최대 3,800만원',
    interestRate: '연 12% ~ 22%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '055-912-1313',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: true,
    consultationType: 'phone',
    consultationTime: '08:30 ~ 21:00',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-37',
    name: '프리랜스금융',
    tagline: '프리랜서·일용직',
    summary: '프리랜서·일용직·프리랜서대출 전문.',
    regionLabel: '서울',
    region: '서울 강서구',
    products: ['프리랜서대출', '일용직대출', '신용대출', '소액대출'],
    loanLimit: '최대 2,000만원',
    interestRate: '연 14% ~ 24%',
    repaymentMethod: '원리금균등',
    contactNumber: '02-913-1414',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '10:00 ~ 21:00',
    situations: ['프리랜서'],
  },
  {
    id: 'company-38',
    name: '달서믿음대부',
    tagline: '달서·수성 직장인',
    summary: '직장인·여성 소액·비상금.',
    regionLabel: '대구',
    region: '대구 달서구',
    products: ['직장인대출', '여성대출', '비상금대출'],
    loanLimit: '최대 2,300만원',
    interestRate: '연 14% ~ 22%',
    repaymentMethod: '원리금균등',
    contactNumber: '053-914-1515',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 19:30',
    situations: ['직장인', '여성'],
  },
  {
    id: 'company-39',
    name: '북구희망금융',
    tagline: '광주 북구·전북 남부',
    summary: '소액·생활비, 무직자 상담 가능.',
    regionLabel: '광주',
    region: '광주 북구',
    products: ['소액대출', '생활비대출', '무직자대출'],
    loanLimit: '최대 1,200만원',
    interestRate: '연 15% ~ 24%',
    repaymentMethod: '만기일시',
    contactNumber: '062-915-1616',
    isVerifiedAvailable: false,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 17:00',
    situations: ['무직자', '주부'],
  },
  {
    id: 'company-40',
    name: '서귀포안심대부',
    tagline: '서귀포·남제주',
    summary: '제주 남부 거주자 비대면·소액.',
    regionLabel: '제주',
    region: '제주 서귀포시',
    products: ['소액대출', '비대면대출', '온라인대출'],
    loanLimit: '최대 1,800만원',
    interestRate: '연 14% ~ 21%',
    repaymentMethod: '원리금균등',
    contactNumber: '064-916-1717',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 17:00',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-41',
    name: '저신용희망금융',
    tagline: '저신용·소액 전문',
    summary: '저신용자 맞춤 소액·비상금 상담.',
    regionLabel: '서울',
    region: '서울 구로구',
    products: ['저신용자대출', '소액대출', '비상금대출'],
    loanLimit: '최대 700만원',
    interestRate: '연 18% ~ 27%',
    repaymentMethod: '만기일시',
    contactNumber: '02-917-1818',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 19:00',
    situations: ['무직자', '직장인'],
  },
  {
    id: 'company-42',
    name: '일산믿음대부',
    tagline: '일산·파주 경기북부',
    summary: '직장인·주부 소액·무방문.',
    regionLabel: '경기',
    region: '경기 파주시',
    products: ['소액대출', '무방문대출', '주부대출', '직장인대출'],
    loanLimit: '최대 2,100만원',
    interestRate: '연 13% ~ 21%',
    repaymentMethod: '원리금균등',
    contactNumber: '031-918-1919',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 21:00',
    situations: ['직장인', '주부'],
  },
  {
    id: 'company-43',
    name: '동래바로금융',
    tagline: '동래·연제 당일',
    summary: '당일·비상금, 직장인·사업자.',
    regionLabel: '부산',
    region: '부산 동래구',
    products: ['당일대출', '비상금대출', '사업자대출'],
    loanLimit: '최대 2,700만원',
    interestRate: '연 13% ~ 22%',
    repaymentMethod: '원리금균등',
    contactNumber: '051-919-2020',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: true,
    consultationType: 'phone',
    consultationTime: '08:00 ~ 21:00',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-44',
    name: '당일전국대부',
    tagline: '전국 당일 승인',
    summary: '당일 한도 조회·승인, 전국 상담.',
    regionLabel: '전국',
    region: '전국',
    products: ['당일대출', '소액대출', '비상금대출', '직장인대출'],
    loanLimit: '최대 3,000만원',
    interestRate: '연 13% ~ 23%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '1588-4444',
    isVerifiedAvailable: true,
    isRecommended: true,
    isAd: false,
    consultationType: 'both',
    consultationTime: '07:00 ~ 23:00',
    description: '전국 당일 한도 조회가 가능한 긴급 자금 상담.',
    situations: ['직장인', '사업자', '프리랜서'],
  },
  {
    id: 'company-45',
    name: '의정부한결금융',
    tagline: '의정부·양주 경기북동',
    summary: '직장인·무직자 소액, 주말 상담.',
    regionLabel: '경기',
    region: '경기 의정부시',
    products: ['직장인대출', '소액대출', '무직자대출'],
    loanLimit: '최대 1,900만원',
    interestRate: '연 14% ~ 22%',
    repaymentMethod: '원리금균등',
    contactNumber: '031-920-2121',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 20:00',
    situations: ['직장인', '무직자'],
  },
  {
    id: 'company-46',
    name: '천안중앙대부',
    tagline: '천안·공주 충남서부',
    summary: '직장인·사업자 신용·소액.',
    regionLabel: '충남',
    region: '충남 천안시 동남구',
    products: ['신용대출', '소액대출', '사업자대출'],
    loanLimit: '최대 2,400만원',
    interestRate: '연 12% ~ 20%',
    repaymentMethod: '원리금균등',
    contactNumber: '041-921-2222',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 19:00',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-47',
    name: '포항동부금융',
    tagline: '경주·포항 동부',
    summary: '대환·추가, 사업자·직장인.',
    regionLabel: '경북',
    region: '경북 경주시',
    products: ['대환대출', '추가대출', '직장인대출', '사업자대출'],
    loanLimit: '최대 4,200만원',
    interestRate: '연 12% ~ 21%',
    repaymentMethod: '원리금균등',
    contactNumber: '054-922-2323',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 20:00',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-48',
    name: '수원중앙대부',
    tagline: '수원·화성 통합',
    summary: '직장인·자영업자 맞춤, 당일 조회.',
    regionLabel: '경기',
    region: '경기 수원시 팔달구',
    products: ['직장인대출', '자영업자대출', '당일대출', '소액대출'],
    loanLimit: '최대 3,200만원',
    interestRate: '연 12% ~ 19%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '031-923-2424',
    isVerifiedAvailable: true,
    isRecommended: true,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '08:30 ~ 21:30',
    situations: ['직장인', '사업자'],
  },
  ...generateExtraMockCompanies(49, 24),
];

export const mockCompanies: Company[] = mockCompanySource.map((company) => ({
  ...company,
  features:
    company.features && company.features.length > 0
      ? company.features.slice(0, 3)
      : buildCompanyFeatures(company),
  supplementaryDescription:
    company.supplementaryDescription ??
    buildSupplementaryDescription(company.name),
  registration: company.registration ?? buildCompanyRegistration(company),
  productDetail: company.productDetail ?? buildCompanyProductDetail(company),
}));

/** @deprecated mockCompanies 사용 권장 */
export const loanCompanyMock = mockCompanies;

export function getCompanyById(id: string): Company | undefined {
  return mockCompanies.find((company) => company.id === id);
}
