import type { Company } from './types';

export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    name: '든든금융대부',
    region: '서울 강남구',
    products: ['소액대출', '무방문대출'],
    loanLimit: '최대 3,000만원',
    interestRate: '연 12% ~ 20%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '02-1234-5678',
    isVerifiedAvailable: true,
    isRecommended: true,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 22:00',
    description:
      '서울 강남·서초 지역 직장인·사업자 대상 소액·비상금 대출 상담을 제공합니다. 비대면 서류 접수가 가능합니다.',
    additionalCost: '중도상환수수료 없음 (조건별 상이)',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-2',
    name: '서울희망금융',
    region: '서울 마포구',
    products: ['비상금대출', '개인돈대출'],
    loanLimit: '최대 5,000만원',
    interestRate: '연 14% ~ 24%',
    repaymentMethod: '원리금균등',
    contactNumber: '02-2345-6789',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: true,
    consultationType: 'phone',
    consultationTime: '10:00 ~ 20:00',
    description: '마포·은평 지역 맞춤 대출 상담. 당일 한도 조회 가능.',
    additionalCost: '취급수수료 별도 안내',
    situations: ['직장인', '프리랜서', '여성'],
  },
  {
    id: 'company-3',
    name: '부산안심대부',
    region: '부산 해운대구',
    products: ['소액대출'],
    loanLimit: '최대 1,000만원',
    interestRate: '연 15% ~ 22%',
    repaymentMethod: '만기일시',
    contactNumber: '051-345-6789',
    isVerifiedAvailable: false,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 18:00',
    description: '부산·울산 지역 소액대출 전문.',
    situations: ['무직자', '주부'],
  },
  {
    id: 'company-4',
    name: '경기믿음금융',
    region: '경기 수원시',
    products: ['소액대출', '월변대출'],
    loanLimit: '최대 2,000만원',
    interestRate: '연 13% ~ 19%',
    repaymentMethod: '원리금균등',
    contactNumber: '031-456-7890',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 21:00',
    description: '수원·용인·화성 지역 직장인·사업자 대출 상담.',
    situations: ['직장인', '사업자'],
  },
  {
    id: 'company-5',
    name: '인천스마트대부',
    region: '인천 남동구',
    products: ['무방문대출', '비상금대출'],
    loanLimit: '최대 2,500만원',
    interestRate: '연 11% ~ 18%',
    repaymentMethod: '원리금균등 · 만기일시',
    contactNumber: '032-567-8901',
    isVerifiedAvailable: true,
    isRecommended: true,
    isAd: true,
    consultationType: 'phone',
    consultationTime: '08:30 ~ 22:30',
    description: '인천 전역 비대면·무방문 대출 상담.',
    situations: ['직장인', '주부', '여성'],
  },
  {
    id: 'company-6',
    name: '대구한결금융',
    region: '대구 수성구',
    products: ['개인돈대출', '소액대출'],
    loanLimit: '최대 4,000만원',
    interestRate: '연 16% ~ 25%',
    repaymentMethod: '원리금균등',
    contactNumber: '053-678-9012',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'both',
    consultationTime: '09:00 ~ 19:00',
    description: '대구·경북 지역 맞춤 대출.',
    situations: ['직장인', '프리랜서'],
  },
  {
    id: 'company-7',
    name: '광주희망대부',
    region: '광주 서구',
    products: ['소액대출', '비상금대출'],
    loanLimit: '최대 1,500만원',
    interestRate: '연 14% ~ 21%',
    repaymentMethod: '만기일시',
    contactNumber: '062-789-0123',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'sms',
    consultationTime: '09:00 ~ 18:00',
    situations: ['무직자', '주부', '여성'],
  },
  {
    id: 'company-8',
    name: '제주안심금융',
    region: '제주 제주시',
    products: ['소액대출', '무방문대출'],
    loanLimit: '최대 2,000만원',
    interestRate: '연 13% ~ 20%',
    repaymentMethod: '원리금균등',
    contactNumber: '064-890-1234',
    isVerifiedAvailable: true,
    isRecommended: false,
    isAd: false,
    consultationType: 'phone',
    consultationTime: '09:00 ~ 17:30',
    description: '제주 지역 거주자 대상 비대면 상담.',
    situations: ['직장인', '사업자', '프리랜서'],
  },
];

/** @deprecated mockCompanies 사용 권장 */
export const loanCompanyMock = mockCompanies;

export function getCompanyById(id: string): Company | undefined {
  return mockCompanies.find((company) => company.id === id);
}
